### ISSUE TITLE
Student cannot register to an elective (no link is created in db file)

### ISSUE THREAD

**Issue by Tanislas** [jniegsch/Group7-PFMAssignment-ElectiveSelection#3]
**Describe the bug**
When a student registers to an elective the stuelectrel file is created but the file is empty.

**To Reproduce**
Create a student user, register for elective as a student. See nothing happening.

**Comment by ChristinaHenninger** [comment]
still not working. shows an error now:

<img width="653" alt="image" src="https://user-images.githubusercontent.com/48248622/53984526-c9f86d80-4119-11e9-8f6c-c402746fb13a.png">
