### ISSUE TITLE
Creating an elective doesn't work

### ISSUE THREAD

**Issue by ChristinaHenninger** [jniegsch/Group7-PFMAssignment-ElectiveSelection#37]
After adding the lecture day of an elective, an error message occurs.

<img width="1036" alt="image" src="https://user-images.githubusercontent.com/48248622/53961087-1925aa80-40e8-11e9-9d9c-69b398f00f91.png">

**Comment by jniegsch** [comment]
Fixed in:
> v0.4.3.3
