### ISSUE TITLE
error when adding elective at the end

### ISSUE THREAD

**Issue by annejanssens** [jniegsch/Group7-PFMAssignment-ElectiveSelection#44]
![image](https://user-images.githubusercontent.com/48250419/53985653-80f5e880-411c-11e9-9ab7-3602452474f1.png)

**Comment by jniegsch** [comment]
Could you attach a screenshot of your `.db/electiveinfo.txt` file? So we can better see what might have gone wrong? @annejanssens

**Comment by annejanssens** [comment]
Sorry I think I made a mistake myself, second time it did work @jniegsch

**Comment by jniegsch** [comment]
What kind of mistake though? If it's something that could happen easily we need to control for it so it doesn't just crash

**Comment by annejanssens** [comment]
@jniegsch i think it is because i did still habe an old file on my computer. After i deleted all the old files, i didnt had the error anymore. Really no clue what else it could have been
