### ISSUE TITLE
Setting title when creating new lecturer does not work properly

### ISSUE THREAD

**Issue by Tanislas** [jniegsch/Group7-PFMAssignment-ElectiveSelection#49]
**Describe the bug**
When creating a new lecturer (Admin dash option #2) and you are requested to select the title, the numbering is off. 

When selecting option 0 it registers DEFAULT in db file. Selecting option 3 registers Ms (so Yashar is a Ms now in my db)

![annotation 2019-03-07 221806](https://user-images.githubusercontent.com/48248187/53989730-ec44b800-4126-11e9-8532-699ebe204986.jpg)

**Comment by jniegsch** [comment]
@Tanislas can you actually handle this bug quickly?

**Comment by Tanislas** [comment]
@jniegsch I'll look into it and if not, I'll reassign

**Comment by Tanislas** [comment]
Changed the order or Title enum in Lecturer class.
Removed option 0 (No title) and set DEFAULT to be option 0. Adjusted the counting in User class.
Tested and now all titles are written to the db file correctly.
![annotation 2019-03-08 121043](https://user-images.githubusercontent.com/48248187/54025579-3a939e80-419b-11e9-9031-7b5075e44883.jpg)
