### ISSUE TITLE
Edited User details are not written to db file

### ISSUE THREAD

**Issue by Tanislas** [jniegsch/Group7-PFMAssignment-ElectiveSelection#50]
**Describe the bug**
When User details are edited (Admin dash option #4), it only stores the new user details as long as you do not log out. It does not write them to the db file so the next time you login the original details are there again.

**Comment by ChristinaHenninger** [comment]
I don't have this problem. If I edit a User, it is changed in the db and also if I call the 'view users' after logging in newly, I see the changed details.

**Comment by Tanislas** [comment]
@ChristinaHenninger Weird. Just tried again with the files from v0.4.3 that I shared on WhatsApp (and which I suppose you use as well?) and I still get this issue.

**Comment by ChristinaHenninger** [comment]
@Tanislas which user do you edit and which attribute? I tried it with lecturer and first name, and student and last name. But both were adapted in the db and after logging in again, both showed the edited details.

**Comment by jniegsch** [comment]
Solved in `v.0.4.4.5`
