### ISSUE TITLE
Giving incorrect input when filtering to find an elective crashes the program

### ISSUE THREAD

**Issue by Tanislas** [jniegsch/Group7-PFMAssignment-ElectiveSelection#52]
**Describe the bug**
When you select "Find an elective" (admin dash option 7) and filtering on any of the four options and you enter something else than the specified input type (e.g. char instead of int, or when you just hit enter) the program crashes.

**Comment by ChristinaHenninger** [comment]
@Tanislas  Chris, do you already have a solution for this issue? I think I found a solution, because I encountered a similar issue.
If you change the code from line 533 until the end of this method:

InternalCore.println("\nThe electives that match your search are: ");
        int optEl = 0;
        if (electives == null) {
        	InternalCore.println("No matches.");
        } else {
        	 for (Elective elect : electives) {
                 InternalCore.println(" " + optId + ") " + elect.toString());
                 optEl++;
             }
             String viewChoice = InternalCore.getUserInput(String.class, "Would you like to view one of the electives details? (y/n)");
             if (viewChoice == null) return;
             if (viewChoice.toLowerCase().equals("y")) {
                 while (true) {
                     Integer electiveChoice = InternalCore.getUserInput(Integer.class, "The elective you would like to view (1, 2, etc.): ");
                     if (electiveChoice == null) break;
                     if (electiveChoice < 1 || electiveChoice > electives.length) break;
                     InternalCore.println(" \n" + InternalCore.consoleLine('-'));
                     InternalCore.println(electives[electiveChoice - 1].view());
                     InternalCore.println();
                     String contChoice = InternalCore.getUserInput(String.class, "Would you like to view another from your search? (y/n)");
                     if (contChoice == null) break;
                     if (contChoice.toLowerCase().equals("y")) {
                         optEl = 0;
                         for (Elective elect : electives) {
                             InternalCore.println(" " + optEl + ") " + elect.toString());
                             optEl++;
                         }
                         continue;
                     }
                     break;
                 }
             }
        } 
    }

**Comment by ChristinaHenninger** [comment]
fixed.
