### ISSUE TITLE
Lecturer dashboard: Option 4: view your grades not working correctly

### ISSUE THREAD

**Issue by annejanssens** [jniegsch/Group7-PFMAssignment-ElectiveSelection#69]
After a lecturer just added a grade, if you push option 4, the system shows the grade correctly.
![image](https://user-images.githubusercontent.com/48250419/54053555-e9f66280-41e7-11e9-8ac1-a91d3546186b.png)

However, after logging out and again logging in, the systems shows the grade is -1.0
![image](https://user-images.githubusercontent.com/48250419/54053625-20cc7880-41e8-11e9-80e0-ec0b31bc7cbb.png)

In the student dashboard: Option 5 even responds to the student that there are no grades yet.
![image](https://user-images.githubusercontent.com/48250419/54053654-42c5fb00-41e8-11e9-90af-ec6a22513fb1.png)

**Comment by jniegsch** [comment]
@annejanssens Could you try to debug and fix it? Not home right now

**Comment by jniegsch** [comment]
Should have been fixed in `v0.4.4.5` 
If it reoccurs, please reopen the issue

**Comment by jniegsch** [comment]
If this is still an issue, please describe in detail what you did before that and attach the database files please

**Comment by jniegsch** [comment]
Seems to be fixed in `v0.4.4.10`
