### ISSUE TITLE
creating a new user doesn't increment the ID number

### ISSUE THREAD

**Issue by ChristinaHenninger** [jniegsch/Group7-PFMAssignment-ElectiveSelection#72]
When creating a new user, the ID for the specific type is not being incremented. always ID 1.

<img width="312" alt="image" src="https://user-images.githubusercontent.com/48248622/54075615-c132a380-42a1-11e9-9883-9c8afb49b935.png">

**Comment by ChristinaHenninger** [comment]
Jan, can you take a look at it?

**Comment by jniegsch** [comment]
Could you check the file database/studentinfo.txt and database/lecturerinfo.txt to see if the IDs are also not being stored properly?

**Comment by ChristinaHenninger** [comment]
yes, that's where I always checked it. 
here as example the student db:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/48248622/54076319-b9c3c800-42aa-11e9-940c-5f5403984a99.png">

**Comment by ChristinaHenninger** [comment]
I've tested it again with lecturer, but same issue:
<img width="461" alt="image" src="https://user-images.githubusercontent.com/48248622/54076334-e4ae1c00-42aa-11e9-9a98-3ea9fb728911.png">

**Comment by jniegsch** [comment]
Alright, I’ll try and fix it tomorrow morning

**Comment by jniegsch** [comment]
Fixed in `v0.4.4.4`
