### ISSUE TITLE
Title numbering

### ISSUE THREAD

**Issue by ChristinaHenninger** [jniegsch/Group7-PFMAssignment-ElectiveSelection#73]
If you create a new user (a lecturer) and you decide on the title, the choice is not equal to what is saved in the db:
- choose 3 (Mrs) --> db: Ms
- choose 5 (Dr) --> db: Prof
- choose 6 (Prof) --> db: DEFAULT
- choose 2 (Mr) --> db: Mrs

**Comment by jniegsch** [comment]
Fixed in `v0.4.4.5`
