### ISSUE TITLE
Errors in the lecturer dashboard

### ISSUE THREAD

**Issue by sandraslotboom** [jniegsch/Group7-PFMAssignment-ElectiveSelection#76]
![Screenshot 2019-03-09 at 21 13 06](https://user-images.githubusercontent.com/48250817/54076848-4329c900-42b0-11e9-8bd6-f86a33d3915e.png)
I get errors in the lecturer dashboard for options 1 to 5

**Comment by jniegsch** [comment]
Could you attach an image of the file `database/stuelectrel.txt`

**Comment by jniegsch** [comment]
Fixed in `v0.4.4.7`
