### ISSUE TITLE
The assignment of a title (e.g. mr) is saved as "no title" #77

### ISSUE THREAD

**Issue by sandraslotboom** [jniegsch/Group7-PFMAssignment-ElectiveSelection#78]
![Screenshot 2019-03-10 at 10 43 32](https://user-images.githubusercontent.com/48250817/54083269-b4559480-4321-11e9-91c1-93ea54331ca1.png)
![Screenshot 2019-03-10 at 10 43 38](https://user-images.githubusercontent.com/48250817/54083271-b61f5800-4321-11e9-9972-e3c7ad0d8bd6.png)

**Comment by jniegsch** [comment]
Did you logout between or not?

**Comment by sandraslotboom** [comment]
No I did not, I logged in for the first time after making an admin account. Then I directly made a lecturer user, but when i then print the users, it shows "no title".

**Comment by jniegsch** [comment]
Fixed in release `v0.4.4.10`
