### ISSUE TITLE
Error when adding a student grade when the student is not yet enrolled in the particular elective

### ISSUE THREAD

**Issue by sandraslotboom** [jniegsch/Group7-PFMAssignment-ElectiveSelection#79]
![Screenshot 2019-03-10 at 10 47 44](https://user-images.githubusercontent.com/48250817/54083341-51183200-4322-11e9-8a88-a0b78457845a.png)
![Screenshot 2019-03-10 at 10 49 05](https://user-images.githubusercontent.com/48250817/54083342-55444f80-4322-11e9-8628-29a5b4bc5ae9.png)
![Screenshot 2019-03-10 at 10 49 35](https://user-images.githubusercontent.com/48250817/54083344-56757c80-4322-11e9-8670-c5054eecd5c0.png)

**Comment by jniegsch** [comment]
Fixed in `v0.4.4.8`
