### ISSUE TITLE
Error when adding a student grade to an elective that is not teached by the particular lecturer

### ISSUE THREAD

**Issue by sandraslotboom** [jniegsch/Group7-PFMAssignment-ElectiveSelection#80]
![Screenshot 2019-03-10 at 10 54 49](https://user-images.githubusercontent.com/48250817/54083401-fe8b4580-4322-11e9-992e-21d1f95f93b9.png)

**Comment by jniegsch** [comment]
Could you rerun with the new version and post the new error message here please

**Comment by annejanssens** [comment]
I also get an issue when trying to add a grade for a course that is teached by a particular teacher
![image](https://user-images.githubusercontent.com/48250419/54083910-4a8db880-432a-11e9-99f1-75b18349a269.png)

![image](https://user-images.githubusercontent.com/48250419/54083916-537e8a00-432a-11e9-9d61-816b9cf1f1f0.png)

**Comment by sandraslotboom** [comment]
No. More. Error. 
now the system allows a lecturer to add a grade to a student (which is indeed enrolled to an elective), but this lecturer is not the lecturer of that particular elective

**Comment by jniegsch** [comment]
Fixed in `v0.4.4.10`
