### ISSUE TITLE
Error when registering a student to a (second) elective 

### ISSUE THREAD

**Issue by sandraslotboom** [jniegsch/Group7-PFMAssignment-ElectiveSelection#81]
![Screenshot 2019-03-10 at 10 56 49](https://user-images.githubusercontent.com/48250817/54083446-da7c3400-4323-11e9-9ca3-eac53dbdaa49.png)

**Comment by jniegsch** [comment]
Could you rerun with the new version and post the new error message here please

**Comment by annejanssens** [comment]
I also have problems when wanting to register for an elective as a student:
![image](https://user-images.githubusercontent.com/48250419/54083876-adcb1b00-4329-11e9-8d5c-42c9c2f31575.png)

**Comment by sandraslotboom** [comment]
MY ERROR IS SOLVEEDDDDDD
