### ISSUE TITLE
Error on viewing enrolled electives (whereas it did work before) 

### ISSUE THREAD

**Issue by sandraslotboom** [jniegsch/Group7-PFMAssignment-ElectiveSelection#82]
![Screenshot 2019-03-10 at 10 57 18](https://user-images.githubusercontent.com/48250817/54083455-fa135c80-4323-11e9-9505-05e9d7d97e55.png)

**Comment by jniegsch** [comment]
Could you rerun with the new version and post the new error message here please

**Comment by sandraslotboom** [comment]
This one works now, also after logging out, logging into lecturerdashboard, and logging back into studentdashboard. I logged in and out a couple of more times and changed grades in between and still works! :)
