### ISSUE TITLE
Error on lecturer dashboard (whereas it did work a minute before) 

### ISSUE THREAD

**Issue by sandraslotboom** [jniegsch/Group7-PFMAssignment-ElectiveSelection#83]
![Screenshot 2019-03-10 at 10 59 36](https://user-images.githubusercontent.com/48250817/54083473-27f8a100-4324-11e9-8138-547e167b46b5.png)
Dimitrios Tsekouras is teaching PFM in this case, and it worked before

**Comment by jniegsch** [comment]
Could you rerun with the new version and post the new error message here please. Also attach the student elective relation file and elective info file

**Comment by sandraslotboom** [comment]
Error = gone!
