### ISSUE TITLE
Error when displaying a student's grade 

### ISSUE THREAD

**Issue by sandraslotboom** [jniegsch/Group7-PFMAssignment-ElectiveSelection#84]
Just assigned an 8 to the student in the lecturer dashboard, which all went fine, but still get this error
![Screenshot 2019-03-10 at 10 58 34](https://user-images.githubusercontent.com/48250817/54083525-ddc3ef80-4324-11e9-8bc0-c2a5b016c5ed.png)

**Comment by jniegsch** [comment]
Could you rerun with the new version and post the new error message here please

**Comment by sandraslotboom** [comment]
error is gone!! :D :D :D you're the best!
