### ISSUE TITLE
error viewing list of registered students

### ISSUE THREAD

**Issue by annejanssens** [jniegsch/Group7-PFMAssignment-ElectiveSelection#85]
I get an error if I want to view list of registered students in lecturer dashboard,
![image](https://user-images.githubusercontent.com/48250419/54083608-f7b20200-4325-11e9-9c57-6c1251b4d9ff.png)

This is what I see in the stuelecectrel file
![image](https://user-images.githubusercontent.com/48250419/54083621-1adcb180-4326-11e9-98e2-feb6785c93d5.png)

**Comment by jniegsch** [comment]
Could you rerun with the new version and post the new error message here please. Also clear out the stuelectrel file please.

**Comment by annejanssens** [comment]
![image](https://user-images.githubusercontent.com/48250419/54083803-f7ffcc80-4328-11e9-96f8-9ee486567a1d.png)

![image](https://user-images.githubusercontent.com/48250419/54083818-182f8b80-4329-11e9-889b-d2de6ee8877d.png)

@jniegsch

**Comment by jniegsch** [comment]
I absolutely cannot recreate the bug with the info I have. I have pushed an update, please clear your database and see if it works then
@annejanssens
