### ISSUE TITLE
Error lecturer dashboard

### ISSUE THREAD

**Issue by sandraslotboom** [jniegsch/Group7-PFMAssignment-ElectiveSelection#86]
Whereas i don't get an error when printing the list of registered students for the PFM elective, (in which 3 students are enrolled and which is taught by the right lecturer: dimitriostsekouras), I do get an error when i'm trying to print the registered students for one of his other electives, e.g. SE in which also one student is enrolled. 
![Screenshot 2019-03-10 at 15 07 23](https://user-images.githubusercontent.com/48250817/54086117-54bdb000-4346-11e9-96a5-5f3b0f2ab003.png)
![Screenshot 2019-03-10 at 15 08 32](https://user-images.githubusercontent.com/48250817/54086122-63a46280-4346-11e9-8344-435434aa83f5.png)
![Screenshot 2019-03-10 at 15 09 43](https://user-images.githubusercontent.com/48250817/54086129-90587a00-4346-11e9-9db1-8f3fec0cfbd2.png)

**Comment by jniegsch** [comment]
I think this is fixed in `v0.4.4.10`
