### ISSUE TITLE
Error in lecturer dashboard 

### ISSUE THREAD

**Issue by sandraslotboom** [jniegsch/Group7-PFMAssignment-ElectiveSelection#87]
Ok, so I was able to add a grade to a student enrolled in an elective not taught by the particular lecturer. This went fine without any error. However, then when i wanted to print the grades for that elective, i did get an error, and afterwards I wasn't able at all anymore to print grades of any electives (also not of those that are taught by the particular lecturer). The elective not taught by this teacher is TEM, whereas PFM is taught by this lecturer. 
![Screenshot 2019-03-10 at 15 12 07](https://user-images.githubusercontent.com/48250817/54086207-a74b9c00-4347-11e9-9391-0a196b78e546.png)
![Screenshot 2019-03-10 at 15 12 48](https://user-images.githubusercontent.com/48250817/54086208-a9adf600-4347-11e9-919f-b0ccddc1caad.png)
![Screenshot 2019-03-10 at 15 13 23](https://user-images.githubusercontent.com/48250817/54086210-ac105000-4347-11e9-992d-3563f5813411.png)

**Comment by sandraslotboom** [comment]
Ok, so now it all starts to trip. I also cannot print the" view electives you teach" from the lecturer dashboard of the lecturer that does teach TEM. Also, my admin dashboard trips now because of this same error.. 
![Screenshot 2019-03-10 at 15 19 47](https://user-images.githubusercontent.com/48250817/54086244-fc87ad80-4347-11e9-8e39-fe389abfbbe8.png)
![Screenshot 2019-03-10 at 15 19 15](https://user-images.githubusercontent.com/48250817/54086247-ff829e00-4347-11e9-9301-7086475ba7b4.png)

**Comment by jniegsch** [comment]
Could you send a picture of the `Student Elective Relation` file? @sandraslotboom

**Comment by jniegsch** [comment]
And the `Elective Info` file?
