### ISSUE TITLE
Lecturer dash: Enter invalid or no value for view options results in crash

### ISSUE THREAD

**Issue by Tanislas** [jniegsch/Group7-PFMAssignment-ElectiveSelection#88]
**Describe the bug**
When logged in as a lecturer:
Use any of the View options (option 2, 3 or 4) -> Enter invalid value or no value -> Hit Enter -> Crash

![Annotation 2019-03-10 153544](https://user-images.githubusercontent.com/48248187/54086731-85084d00-434c-11e9-9a6d-3ded24539587.jpg)

**Comment by jniegsch** [comment]
Should be fixed in `v0.4.4.10`
