### ISSUE TITLE
Invalid DoB does not give prompt but is converted to a valid date

### ISSUE THREAD

**Issue by Tanislas** [jniegsch/Group7-PFMAssignment-ElectiveSelection#89]
**Is your feature request related to a problem? Please describe.**
When you enter an invalid date, it does not give an error prompt but instead converts it to a valid date trough addition somehow.

Examples:
(1970-13-02 is saved as 1971-01-02)
(2080-55-99 is saved as 2084-10-07)

![Annotation 2019-03-10 162616](https://user-images.githubusercontent.com/48248187/54087618-da485c80-4354-11e9-95ad-8d98ed811788.jpg)

**Comment by jniegsch** [comment]
Could you show me what it is saved as in the db? @Tanislas

**Comment by Tanislas** [comment]
@jniegsch 

Lecturer nr 4 (the bottom one named Otto) was converted from 1970-13-02 to 1971-01-02
![Lecturer nr4 (Otto)](https://user-images.githubusercontent.com/48248187/54088147-30b89980-435b-11e9-8f2b-dabc0e48ccf3.jpg)

Student nr 1 (top one named Chris) was converted from 2080-55-99 to 2084-10-07
![Student nr1 (Chris)](https://user-images.githubusercontent.com/48248187/54088183-9c9b0200-435b-11e9-9df6-fb16f6642aaf.jpg)

**Comment by jniegsch** [comment]
Well it’s technically doing the right thing, right? I’ll put it to the dev priority list as point 4, so if we finish the one before (point 3) we can implement that.

**Comment by jniegsch** [comment]
Added in `v1.0`
