### ISSUE TITLE
View user --> title shows as "no Title"

### ISSUE THREAD

**Issue by ChristinaHenninger** [jniegsch/Group7-PFMAssignment-ElectiveSelection#90]
When logged in as Admin and calling method "view users" (3), the lecturers are not shown with their titles:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/48248622/54088490-bd188b80-435e-11e9-843a-d4e3de084ccd.png">

However, the database has the correct information stored:
<img width="436" alt="image" src="https://user-images.githubusercontent.com/48248622/54088470-a70acb00-435e-11e9-94ce-e8aea253e256.png">

**Comment by jniegsch** [comment]
Is this with the newest version? @ChristinaHenninger

**Comment by ChristinaHenninger** [comment]
@jniegsch Yes, I just downloaded the newest version maybe 30 minutes ago and I am working with that one now.

**Comment by jniegsch** [comment]
Could you try to debug it yourself?

**Comment by ChristinaHenninger** [comment]
Yes :)

Verstuurd vanaf mijn iPhone

**Comment by ChristinaHenninger** [comment]
@jniegsch ,okay, so new discovery:
I create a new lecturer as admin.
- if I call the "view user" method in the same session, it shows "no title." lecture name...
- if I close the session and log in newly, it shows the correct title

Is there a special process going on during logging out or signing in?

**Comment by jniegsch** [comment]
It would just mean it’s not being successfully added to the session memory, i thought I had fixed it though. I’ll try it again when I’m home and see if I can fix it.

**Comment by jniegsch** [comment]
Cannot recreate in `v0.4.4.11`. Will thus close the issue, please reopen if it still persists in the newest version.
