### ISSUE TITLE
Lecturer method: see electives you teach

### ISSUE THREAD

**Issue by ChristinaHenninger** [jniegsch/Group7-PFMAssignment-ElectiveSelection#91]
Lecturer dashboard --> method (6): view all electives you teach
in this example: lecturer teaches one elective 'programming'
error message:
<img width="739" alt="image" src="https://user-images.githubusercontent.com/48248622/54090342-8862ff00-4373-11e9-96fe-523ab800f5f6.png">

**Comment by jniegsch** [comment]
Could you attach the database files for the elective and student elective relationship? @ChristinaHenninger

**Comment by ChristinaHenninger** [comment]
yes, give me one second. I think actually I made a mistake and it's not the program's mistake, but mine...

**Comment by jniegsch** [comment]
In what way did you make a mistake you think?

**Comment by ChristinaHenninger** [comment]
hm....I could recreate the 'issue'. I deleted my databases and did the following:
- create one elective --> ID: 4
- edit this elective --> ID is added once more to the db (see first two numbers in the screenshot)

<img width="495" alt="image" src="https://user-images.githubusercontent.com/48248622/54090449-ab41e300-4374-11e9-8bd6-bfc3ff2e6f1e.png">

I think this is then the issue for the error message.

**Comment by jniegsch** [comment]
You have created it in the file/entry? Or you created it through the system?

**Comment by ChristinaHenninger** [comment]
I create everything through the system. So, admin dashboard --> method 5: create new elective; and then also via the same dashboard --> method 6: edit elective
...it doesn't matter which attribute of elective I edit; the ID is always saved twice.

**Comment by jniegsch** [comment]
Fixed in `v0.4.4.12`
