### ISSUE TITLE
Necessary variables?

### ISSUE THREAD

**Issue by ChristinaHenninger** [jniegsch/Group7-PFMAssignment-ElectiveSelection#92]
Do we need these variables? I searched the classes for it, but couldn't find that these were used:
User class:
- User[] all students (figure 1)
- boolean hasValidStudentUsers (figure 1)
- boolean loggedIn (figure 2)

<img width="903" alt="image" src="https://user-images.githubusercontent.com/48248622/54091094-2eb30280-437c-11e9-87fc-88c22d9033c6.png">

<img width="890" alt="image" src="https://user-images.githubusercontent.com/48248622/54091116-65891880-437c-11e9-8aa9-291134b88a37.png">

**Comment by jniegsch** [comment]
Leave them for now, I’ll do spring cleaning tomorrow

**Comment by ChristinaHenninger** [comment]
👍

**Comment by jniegsch** [comment]
Done in `v1.0`
