### ISSUE TITLE
grade is not deleted after changing elective

### ISSUE THREAD

**Issue by ChristinaHenninger** [jniegsch/Group7-PFMAssignment-ElectiveSelection#94]
- register to a course as student
- give a grade to this student as a lecturer
- change the course as a student
- --> grade is not deleted, but is displayed then for the new course

Is this a problem? Or are we fine with that?

<img width="622" alt="image" src="https://user-images.githubusercontent.com/48248622/54136816-bd775c00-441c-11e9-838d-8944063ee23d.png">
in this example:
- Student1 was registered to BMME001
- Student1 was assigned a grade of 7.9 for BMME001
- Student3 changed the elective to BMME003 --> grade is still visible

**Comment by annejanssens** [comment]
I am fine with it, I think. Because in the normal world after you have received a grade, you are not able to switch anymore. 
But if it is easy for @jniegsch  to put a reset function in when a student switches, than I would prefer that :)
@ChristinaHenninger

**Comment by jniegsch** [comment]
How about a block if you have received a grade instead?

**Comment by ChristinaHenninger** [comment]
@jniegsch oh, that's a great idea! If it's easy to implement, then I think that's a very nice additional feature. 👍

**Comment by ChristinaHenninger** [comment]
issue solved.
