### ISSUE TITLE
Asking for the grade of an elective the student doesn't take

### ISSUE THREAD

**Issue by ChristinaHenninger** [jniegsch/Group7-PFMAssignment-ElectiveSelection#95]
- logged in as a student
- calling method (5) --> "no" asking for specific course grade
- asking for a course, that exists but that the student is not registered in

<img width="801" alt="image" src="https://user-images.githubusercontent.com/48248622/54137183-7342aa80-441d-11e9-8ec2-cd316991dc53.png">

Error in the "Registration" class in the method "isNotRegisteredForElective" (line36).

**Comment by ChristinaHenninger** [comment]
quick note: I added the '4' for the first question with the mission to try and break the program ;)

**Comment by jniegsch** [comment]
Should be fixed in `v0.4.4.13` please double check
