### ISSUE TITLE
Creating a lecturer without input for title crashes the program

### ISSUE THREAD

**Issue by Tanislas** [jniegsch/Group7-PFMAssignment-ElectiveSelection#96]
**Describe the bug**
When you are creating a lecturer and you do not select a title for the lecturer but just hit enter, the program crashes

![Annotation 2019-03-11 171607 Lecturer no title crash](https://user-images.githubusercontent.com/48248187/54139287-7fc90200-4421-11e9-9270-7b6506ecd43c.jpg)

**Comment by jniegsch** [comment]
Fixed in `v0.4.4.14`
